In [1]:
#print("Daivame")


In [2]:
import os
import re
import numpy as np

models = ['Model_1','Model_2','Model_3','Model_4']


nd_array_dev = np.zeros((4,16)) #Models X Configs
nd_array_unseen = np.zeros((4,16)) #Models X Configs


In [3]:
for index_m,model in enumerate(models):
    
    currentWorkingDir = '/Users/anupamachingacham/Documents/Learning/M2_NLP_Lorraine/DeepLearning/SP-SYNTAX-PAR/Code/Evaluation/'+model
    
    
    try:
        
        os.chdir(currentWorkingDir)
        currentWorkingDir = os.getcwd()
        
        #print(model)
        
        listDir = [c for c in os.listdir() if "config" in c]              
        temp = [int(l.split('config')[1]) for l in listDir]
        temp.sort()
        listDir = ["config"+str(t) for t in temp]
        
        #print(listDir)
        
        
        for index_c,config in enumerate(listDir):
            
            #print(config)
            
            for file in os.listdir(currentWorkingDir+'/'+config):
                os.chdir(currentWorkingDir+'/'+config)

                if "Dev_Evaluation_Results.csv" in file:
                    
                    with open(file,encoding="utf8") as f:
                        measures = f.readlines()
               
                    f_measure = (measures[1]).split(',')[13]   #f-measure for total
                    #dev_dictonary[model][config] = f_measure
                    
                    nd_array_dev[index_m][index_c] = f_measure

    
                if "Unseen_Evaluation_Results.csv" in file:
                    #print(file)
                    with open(file,encoding="utf8") as f:
                        measures = f.readlines()
               
                    f_measure = (measures[1]).split(',')[13]   #f-measure for total
                    #unseen_dictonary[model][config] = f_measure
                    
                    nd_array_unseen[index_m][index_c] = f_measure
    
    except:
        
        Exception("FileNotFoundError")
    

In [4]:
print(nd_array_dev.T)

[[ 0.764  0.822  0.635  0.792]
 [ 0.767  0.822  0.639  0.792]
 [ 0.768  0.822  0.638  0.793]
 [ 0.     0.332  0.079  0.046]
 [ 0.     0.332  0.077  0.049]
 [ 0.     0.332  0.077  0.049]
 [ 0.248  0.421  0.272  0.312]
 [ 0.038  0.     0.031  0.   ]
 [ 0.143  0.157  0.089  0.114]
 [ 0.053  0.042  0.026  0.   ]
 [ 0.75   0.825  0.639  0.781]
 [ 0.018  0.     0.075  0.043]
 [ 0.741  0.816  0.655  0.774]
 [ 0.015  0.074  0.026  0.007]
 [ 0.293  0.35   0.108  0.205]
 [ 0.012  0.     0.093  0.012]]


In [6]:
print(nd_array_unseen.T)

[[ 0.004  0.018  0.061  0.056]
 [ 0.004  0.018  0.061  0.056]
 [ 0.004  0.018  0.061  0.056]
 [ 0.     0.     0.001  0.002]
 [ 0.     0.     0.002  0.002]
 [ 0.     0.     0.002  0.002]
 [ 0.001  0.     0.022  0.014]
 [ 0.     0.     0.003  0.   ]
 [ 0.     0.     0.004  0.003]
 [ 0.     0.     0.     0.   ]
 [ 0.008  0.018  0.064  0.051]
 [ 0.     0.     0.002  0.003]
 [ 0.006  0.017  0.068  0.058]
 [ 0.     0.     0.     0.   ]
 [ 0.001  0.001  0.012  0.01 ]
 [ 0.     0.     0.002  0.   ]]
